---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = ">",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# dlmtree

`dlmtree` is an R package that provides constrained distributed lag models (DLMs) using a regression tree approach within the Bayesian additive regression trees (BART) framework, referred to as treed DLMs. The package includes various extensions of treed DLMs, allowing for the incorporation of different scenarios like linear, non-linear associations, mixture exposures, and heterogeneous exposure effects. The package is built user-friendly with a single function \texttt{dlmtree} with three arguments to specify treed DLMs. Functions for summarizing the model fit and visualization are also provided.

<!-- badges: start -->
<!-- badges: end -->

### Treed DLM

| Model                                                      | Type          |  Family    | Mixture   | Heterogeneity  |
|:-----------------------------------------------------------|:-------------:|:----------:|:---------:|:--------------:|
| Treed distributed lag model (TDLM)                         | Linear        |  Gaussian  | X         | X              |
|                                                            |               |  Binary    | X         | X              |
|                                                            |               |  Count     | X         | X              |
| Treed distributed lag mixture model (TDLMM)                | Linear        |  Gaussian  | O         | X              |
|                                                            |               |  Binary    | O         | X              |
|                                                            |               |  Count     | O         | X              |
| Treed distributed non-linear lag model (TDLNM)             | Non-linear    |  Gaussian  | X         | X              |
|                                                            |               |  Binary    | X         | X              |
|                                                            | Monotone      |  Gaussian  | X         | X              |
|                                                            |               |  Binary    | X         | X              |
| Heterogeneous distributed lag model (HDLM)                 | Linear        |  Gaussian  | X         | O              |
| Heterogeneous distributed lag mixture model (HDLMM)        | Linear        |  Gaussian  | O         | O              |


### Installation

Installing package from [GitHub](https://github.com/):

``` r
# install.packages("devtools")
devtools::install_github("danielmork/dlmtree")
library(dlmtree)
```

<!-- Installing package from CRAN with: -->

<!-- ``` r -->
<!-- install.packages("dlmtree") -->
<!-- library(dlmtree) -->
<!-- ``` -->
