---
title: "HDLMM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HDLMM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>"
)
```

This vignette demonstrates the implementation of heterogeneous treed distributed lag mixture model (HDLMM).

```{r setup, message = FALSE}
library(dlmtree)
library(tidyverse)
set.seed(1)
data("sbd_dlmtree")
```

### Data preparation
```{r}
# Response and covariates
sbd_cov <- sbd_dlmtree %>% 
            select(bwgaz, ChildSex, MomAge, GestAge, MomPriorBMI, Race,
                    Hispanic, MomEdu, SmkAny, Marital, Income,
                    EstDateConcept, EstMonthConcept, EstYearConcept)

# Exposure data
sbd_exp <- list(PM25 = sbd_dlmtree %>% select(starts_with("pm25_")),
                TEMP = sbd_dlmtree %>% select(starts_with("temp_")),
                SO2 = sbd_dlmtree %>% select(starts_with("so2_")),
                CO = sbd_dlmtree %>% select(starts_with("co_")),
                NO2 = sbd_dlmtree %>% select(starts_with("no2_")))
sbd_exp <- sbd_exp %>% lapply(as.matrix)
```

### Fitting the model
```{r hdlmm.fit}
# Gaussian
hdlmm.fit <- dlmtree(formula = bwgaz ~ ChildSex + MomAge + MomPriorBMI +
                                        Race + Hispanic + SmkAny + EstMonthConcept,
                     data = sbd_cov,
                     exposure.data = sbd_exp,
                     family = "gaussian",
                     dlm.type = "linear", mixture = TRUE, het = TRUE,
                     hdlm.modifiers = c("ChildSex", "MomAge", "MomPriorBMI", "SmkAny"),
                     hdlm.modifier.splits = 15,
                     n.burn = 2500, n.iter = 10000, n.thin = 5)
```

### Model fit summary
```{r hdlmm.sum}
hdlmm.sum <- summary(hdlmm.fit)
hdlmm.sum
```

### Launching Shiny app
```{r hdlmm.shiny}
# shiny(hdlmm.fit)
```

