---
title: "HDLM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HDLM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette demonstrates the implementation of heterogeneous treed distributed lag model (HDLM). More details can be found in Mork et al. (2024) <doi: [10.1080/01621459.2023.2258595](https://doi.org/10.1080/01621459.2023.2258595)>.

```{r setup}
library(dlmtree)
set.seed(1)
```

### Fitting the model
```{r hdlm.fit}
# Gaussian 
D <- sim.hdlmm(sim = "A", n = 5000)
fit <- dlmtree(y ~ ., 
               data = D$dat,
               exposure.data = D$exposure,
               dlm.type = "linear", 
               family = "gaussian", 
               het = TRUE,
               hdlm.dlmtree.type = "shared", # 'nested' is also an option
               n.burn = 2500, n.iter = 10000, n.thin = 5)
```

### Model fit summary
```{r hdlm.sum}
fit_sum <- summary(fit)
fit_sum
```

### Launching Shiny app
```{r hdlm.shiny}
# shiny(fit)
```