---
title: "HDLM"
resource_files:
  - vignettes/articles/sbd_dlmtree.rda
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette demonstrates the implementation of heterogeneous treed distributed lag model (HDLM). More details can be found in Mork et al. (2024) <doi: [10.1080/01621459.2023.2258595](https://doi.org/10.1080/01621459.2023.2258595)>.

```{r setup, message = FALSE}
library(dlmtree)
library(dplyr)
set.seed(1)
```

### Load data

Simulated data is available on [GitHub](https://github.com/danielmork/dlmtree/tree/master/vignettes/articles). It can be loaded with the following code.

```{r load data from GitHub, eval=FALSE, include=TRUE}
sbd_dlmtree <- get_sbd_dlmtree()
```


```{r load data, include=FALSE}
load("sbd_dlmtree.rda")
```

### Data preparation
```{r}
# Response and covariates
sbd_cov <- sbd_dlmtree %>% 
            select(bwgaz, ChildSex, MomAge, GestAge, MomPriorBMI, Race,
                    Hispanic, MomEdu, SmkAny, Marital, Income,
                    EstDateConcept, EstMonthConcept, EstYearConcept)

# Exposure data
sbd_exp <- list(PM25 = sbd_dlmtree %>% select(starts_with("pm25_")),
                TEMP = sbd_dlmtree %>% select(starts_with("temp_")),
                SO2 = sbd_dlmtree %>% select(starts_with("so2_")),
                CO = sbd_dlmtree %>% select(starts_with("co_")),
                NO2 = sbd_dlmtree %>% select(starts_with("no2_")))
sbd_exp <- sbd_exp %>% lapply(as.matrix)
```

### Fitting the model
```{r hdlm.fit}
hdlm.fit <- dlmtree(formula = bwgaz ~ ChildSex + MomAge + MomPriorBMI +
                                        Race + Hispanic + SmkAny + EstMonthConcept,
                    data = sbd_cov,
                    exposure.data = sbd_exp[["PM25"]],
                    family = "gaussian", dlm.type = "linear", het = TRUE,
                    hdlm.modifiers = c("ChildSex", "MomAge", "MomPriorBMI", "SmkAny"),
                    hdlm.modifier.splits = 15,
                    n.burn = 2500, n.iter = 10000, n.thin = 5)
```

### Model fit summary
```{r hdlm.sum}
hdlm.sum <- summary(hdlm.fit)
hdlm.sum
```

### Launching Shiny app
```{r hdlm.shiny}
# shiny(hdlm.fit)
```