---
title: "TDLM"
resource_files:
  - vignettes/articles/sbd_dlmtree.rda
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>"
)
```

This vignette demonstrates the implementation of treed distributed lag model (TDLM). More details can be found in Mork and Wilson (2023) <doi: [10.1111/biom.13568](https://doi.org/10.1111/biom.13568)>.

```{r setup, message = FALSE}
library(dlmtree)
library(dplyr)
set.seed(1)
```

### Load data

Simulated data is available on [GitHub](https://github.com/danielmork/dlmtree/tree/master/vignettes/articles). It can be loaded with the following code.

```{r load data from GitHub, eval=FALSE, include=TRUE}
sbd_dlmtree <- get_sbd_dlmtree()
```


```{r load data, include=FALSE}
load("sbd_dlmtree.rda")
```

### Data preparation
```{r}
# Response and covariates
sbd_cov <- sbd_dlmtree %>% 
            select(bwgaz, ChildSex, MomAge, GestAge, MomPriorBMI, Race,
                    Hispanic, MomEdu, SmkAny, Marital, Income,
                    EstDateConcept, EstMonthConcept, EstYearConcept)

# Exposure data
sbd_exp <- list(PM25 = sbd_dlmtree %>% select(starts_with("pm25_")),
                TEMP = sbd_dlmtree %>% select(starts_with("temp_")),
                SO2 = sbd_dlmtree %>% select(starts_with("so2_")),
                CO = sbd_dlmtree %>% select(starts_with("co_")),
                NO2 = sbd_dlmtree %>% select(starts_with("no2_")))
sbd_exp <- sbd_exp %>% lapply(as.matrix)
```


### Fitting the model
```{r tdlm.fit}
tdlm.fit <- dlmtree(formula = bwgaz ~ ChildSex + MomAge + MomPriorBMI +
                                        Race + Hispanic + SmkAny + EstMonthConcept,
                    data = sbd_cov,
                    exposure.data = sbd_exp[["PM25"]], # A single numeric matrix
                    family = "gaussian", dlm.type = "linear",
                    n.burn = 2500, n.iter = 10000, n.thin = 5)
```

### Model fit summary
```{r tdlm.sum}
tdlm.sum <- summary(tdlm.fit)
tdlm.sum
```

### Exposure effect
```{r tdlm.plot}
plot(tdlm.sum, 
     main = "Plot title", 
     xlab = "Time axis label", 
     ylab = "Exposure effect axis label")
```