# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppIntersection <- function(A, B) {
    .Call(`_dlmtree_cppIntersection`, A, B)
}

dlnmEst <- function(dlnm, predAt, nlags, nsamp, center, se) {
    .Call(`_dlmtree_dlnmEst`, dlnm, predAt, nlags, nsamp, center, se)
}

dlmEst <- function(dlm, nlags, nsamp) {
    .Call(`_dlmtree_dlmEst`, dlm, nlags, nsamp)
}

mixEst <- function(dlm, nlags, nsamp) {
    .Call(`_dlmtree_mixEst`, dlm, nlags, nsamp)
}

tdlmm_Cpp <- function(model) {
    .Call(`_dlmtree_tdlmm_Cpp`, model)
}

tdlnm_Cpp <- function(model) {
    .Call(`_dlmtree_tdlnm_Cpp`, model)
}

