# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param R Vector of responses
#' @param Z Model matrix of covariates
#' @param V Posterior covariance for gamma
#' @param Vchol chol(V)
#' @param sigma2 Current estimate of sigma2
#' @param sumTermXP Number of terminal nodes in model times number of DLM times
#' @param sumFexp Sum over trees of theta * lambda inverse * theta transpose / tau
#'
#' @return List of
#' * new sigma2 estimate
#' * new gamma estimate
#' * new xi estimate (sigma2 hyperparameter)
controlEst <- function(R, Z, V, Vchol, sigma2, sumTermXP, sumFexp) {
    .Call(`_dlmtree_controlEst`, R, Z, V, Vchol, sigma2, sumTermXP, sumFexp)
}

dlnmEst <- function(dlnm, xsplits, nlags, nsamp, center, se, smooth, dlm) {
    .Call(`_dlmtree_dlnmEst`, dlnm, xsplits, nlags, nsamp, center, se, smooth, dlm)
}

#' @param
#'
#' @return
dlnmMHR1 <- function(Y, Z, XX, ZtX, VgZtX, Vg, Xd, ZY, LInv, sigma) {
    .Call(`_dlmtree_dlnmMHR1`, Y, Z, XX, ZtX, VgZtX, Vg, Xd, ZY, LInv, sigma)
}

#' @param
#'
#' @return
dlnmMHR <- function(Y, Z, ZtX, VgZtX, Vg, Xd, ZY, LInv, sigma) {
    .Call(`_dlmtree_dlnmMHR`, Y, Z, ZtX, VgZtX, Vg, Xd, ZY, LInv, sigma)
}

nodeCount <- function(X, Z, Vg, parCount, xmin, xmax, tmin, tmax) {
    .Call(`_dlmtree_nodeCount`, X, Z, Vg, parCount, xmin, xmax, tmin, tmax)
}

nodeCountSE <- function(X, SE, Z, Vg, parCount, xmin, xmax, tmin, tmax) {
    .Call(`_dlmtree_nodeCountSE`, X, SE, Z, Vg, parCount, xmin, xmax, tmin, tmax)
}

